### ISSUE TITLE
Allowing MiniCocoon to be Clonable

### ISSUE THREAD

**Issue by Deaths-Door** [fadeevab/cocoon#29]
There seems no reason MiniCoccon is not `Cloneable` , as [Zeroisizing](https://docs.rs/zeroize/1.8.1/zeroize/struct.Zeroizing.html#impl-Clone-for-Zeroizing%3CZ%3E), [StdRng](https://docs.rs/rand/latest/rand/rngs/struct.StdRng.html#impl-Clone) , and [array](https://doc.rust-lang.org/std/primitive.array.html#impl-Clone-for-%5BT;+N%5D) are all `Cloneable` , and even [CocoonConfig](https://docs.rs/cocoon/latest/src/cocoon/header.rs.html#50) is.

**Comment by fadeevab** [comment]
@Deaths-Door Resolved in the version 0.4.3
